apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: voting-app
spec:
  template:
    metadata:
      name: redis
      labels:
        app: redis
        type: backend
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
  selector:
    matchLabels:
      app: redis
      type: backend
  replicas: 1