apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: voting-app
spec:
  template:
    metadata:
      name: worker
      labels:
        app: worker
        type: backend
    spec:
      containers:
        - name: worker
          image: dockersamples/examplevotingapp_worker
  selector:
    matchLabels:
      app: worker
      type: backend
  replicas: 1