apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result-service
    type: frontend
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: result
    type: frontend
