apiVersion: v1
kind: Pod
metadata:
  name: result
  labels:
    name: result
    type: frontend
spec:
  containers:
    - name: result
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80