apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: vote-service
    type: frontend
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: vote
    type: frontend
