apiVersion: v1
kind: Pod
metadata:
  name: vote
  labels:
    name: vote
    type: frontend
spec:
  containers:
    - name: vote
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80