apiVersion: v1
kind: Pod
metadata:
  name: worker
  labels:
    name: worker
    type: backend
spec:
  containers:
    - name: worker
      image: dockersamples/examplevotingapp_worker
      ockersamples/examplevotingapp_worker