apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db-service
    type: backend
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: postgres
    type: backend