apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis-service
    type: backend
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    app: redis
    type: backend